# Generated by Django 6.0.6 on 2026-06-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('weight_kg', models.CharField(max_length=100)),
                ('activity_level', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('lean_body_mass_kg', models.CharField(max_length=100)),
                ('bmr', models.CharField(max_length=100)),
                ('protein_need_per_lean_kg_sedentary', models.CharField(max_length=100)),
                ('protein_need_per_lean_kg_active', models.CharField(max_length=100)),
                ('protein_need_per_lean_kg_very_active', models.CharField(max_length=100)),
                ('protein_per_kg_min', models.CharField(max_length=100)),
                ('protein_per_kg_moderate', models.CharField(max_length=100)),
                ('protein_per_kg_max', models.CharField(max_length=100)),
                ('activity_protein_multiplier', models.CharField(max_length=100)),
                ('adjusted_protein_need', models.CharField(max_length=100)),
                ('age_protein_factor', models.CharField(max_length=100)),
                ('protein_for_age_group', models.CharField(max_length=100)),
                ('gender_protein_base', models.CharField(max_length=100)),
                ('protein_gender_adjusted', models.CharField(max_length=100)),
                ('purpose_protein_multiplier', models.CharField(max_length=100)),
                ('protein_for_purpose', models.CharField(max_length=100)),
                ('lean_to_total_ratio', models.CharField(max_length=100)),
                ('muscle_mass_score', models.CharField(max_length=100)),
                ('bmr_per_kg', models.CharField(max_length=100)),
                ('protein_metabolic_need', models.CharField(max_length=100)),
                ('training_intensity', models.CharField(max_length=100)),
                ('recovery_protein_need', models.CharField(max_length=100)),
                ('protein_g', models.CharField(max_length=100)),
            ],
        ),
    ]
