# Generated by Django 6.0.6 on 2026-06-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein_pulse_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Height_cm', models.CharField(max_length=100)),
                ('Weight_kg', models.CharField(max_length=100)),
                ('Activity_Level', models.CharField(max_length=100)),
                ('Fitness_Goal', models.CharField(max_length=100)),
                ('Meals_Per_Day', models.CharField(max_length=100)),
                ('FitnessExperience', models.CharField(max_length=100)),
            ],
        ),
    ]
