# Generated by Django 6.0.6 on 2026-06-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein_pulse_ai', '0002_predictdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictData',
            new_name='ProteiDataHist',
        ),
    ]
