# Generated by Django 6.0.6 on 2026-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein_pulse_ai', '0003_rename_predictdata_proteidatahist'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteidatahist',
            name='protein_g',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
